### ISSUE TITLE
some questions about adt design mode

### ISSUE THREAD

**Issue by dandingol03** [dandar3/eclipse-adt-plugin#1]
Hi
  i am a student.Recently,i was trying to understand the process of translating layout xml to graphic in adt,but i get stuck.I was wondering if u can give me some opinion about the translate process.
  thanks for your time~

**Comment by dandar3** [comment]
Hi @dandingol03,

I don't know much about the internals of Google ADT plugin, sorry I can't help you too much in that direction, you could have a look at its sources here:
https://android.googlesource.com/platform/sdk/+/master/eclipse/plugins/

See https://android.googlesource.com/platform/sdk/ for checking the sources out:
`git clone https://android.googlesource.com/platform/sdk/`

`AndroidXmlEditor.java` looks quite inviting to start with:
https://android.googlesource.com/platform/sdk/+/master/eclipse/plugins/com.android.ide.eclipse.adt/src/com/android/ide/eclipse/adt/internal/editors/

**Comment by dandar3** [comment]
I would also suggest following Eclipse Andmore plugin, that is still in active development and you can look at existing tickets and changes applied in them, they might give you an idea about what is what.

- https://projects.eclipse.org/projects/tools.andmore
- https://github.com/eclipse/andmore/
